###
GET http://localhost:8081/oauth/access_token/5tq23ixD

###
POST http://localhost:8081/oauth/access_token
Content-Type: application/json

{
  "grant_type": "password",
  "username": "satya@email.com",
  "password": "ms1"
}